export const relationshipsAndCommunicationSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Nurturing Healthy Relationships and Communication",
  description:
    "Discover how Saora helps you build better relationships and improve communication through sound therapy. Learn about connection, emotional intelligence, and effective communication skills.",
  url: "https://saora.app/solutions/relationships-and-communication",
  mainEntity: {
    "@type": "Article",
    headline: "Nurturing Healthy Relationships and Communication",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "relationships",
      "communication",
      "emotional intelligence",
      "connection",
      "sound therapy",
      "relationship building",
      "communication skills",
      "emotional awareness",
      "interpersonal skills",
      "mental well-being",
      "conflict resolution",
      "active listening",
      "empathy",
      "guided exercises",
      "relaxation techniques",
      "soundscapes",
      "emotional expression",
      "relationship health",
      "communication patterns",
      "personal growth",
    ],
  },
};
