export const mentalPreparationSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Mental Preparation and Performance",
  description:
    "Discover how Saora helps you prepare mentally for peak performance through sound therapy. Learn about focus, visualization, and performance optimization techniques.",
  url: "https://saora.app/solutions/mental-preparation",
  mainEntity: {
    "@type": "Article",
    headline: "Mental Preparation and Performance",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "mental preparation",
      "performance optimization",
      "focus enhancement",
      "visualization",
      "sound therapy",
      "peak performance",
      "mental imagery",
      "stress management",
      "confidence building",
      "emotional regulation",
      "performance anxiety",
      "guided sessions",
      "soundscapes",
      "mental training",
      "preparation techniques",
      "performance psychology",
      "mental resilience",
      "concentration",
      "mind training",
      "well-being",
    ].join(", "),
  },
};
