export const habitsAndBehaviorsSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Building Positive Habits and Behaviors",
  description:
    "Discover how Saora helps you build positive habits and change behaviors through sound therapy. Learn about habit formation, behavior change, and natural solutions for lasting transformation.",
  url: "https://saora.app/solutions/habits-and-behaviors",
  mainEntity: {
    "@type": "Article",
    headline: "Building Positive Habits and Behaviors",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "habits",
      "behavior change",
      "habit formation",
      "positive habits",
      "sound therapy",
      "behavioral transformation",
      "habit tracking",
      "motivation",
      "consistency",
      "routine building",
      "sleep habits",
      "stress management",
      "guided sessions",
      "progress tracking",
      "well-being",
      "personal development",
      "lifestyle changes",
      "habit optimization",
      "behavioral patterns",
      "self-improvement",
    ].join(", "),
  },
};
