export const lifeChangesAndAdaptationSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Navigating Life Changes and Adaptation",
  description:
    "Discover how Saora helps you navigate life changes and transitions through sound therapy. Learn about resilience, emotional support, and growth mindset for better adaptation.",
  url: "https://saora.app/solutions/life-changes-and-adaptation",
  mainEntity: {
    "@type": "Article",
    headline: "Navigating Life Changes and Adaptation",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "life changes",
      "adaptation",
      "transitions",
      "resilience",
      "sound therapy",
      "emotional support",
      "growth mindset",
      "change management",
      "personal development",
      "mental well-being",
      "stress reduction",
      "emotional balance",
      "guided sessions",
      "sleep improvement",
      "soundscapes",
      "life transitions",
      "coping strategies",
      "personal growth",
      "emotional stability",
      "well-being",
    ],
  },
};
