export const selfConfidenceAndSelfEsteemSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Building Self-Confidence and Self-Esteem",
  description:
    "Discover how Saora helps you build self-confidence and self-esteem through sound therapy. Learn about self-compassion, positive affirmations, and personal growth techniques.",
  url: "https://saora.app/solutions/self-confidence-and-self-esteem",
  mainEntity: {
    "@type": "Article",
    headline: "Building Self-Confidence and Self-Esteem",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "self-confidence",
      "self-esteem",
      "personal growth",
      "self-compassion",
      "positive affirmations",
      "sound therapy",
      "confidence building",
      "self-worth",
      "personal development",
      "mental well-being",
      "anxiety relief",
      "self-improvement",
      "positive thinking",
      "guided sessions",
      "progress tracking",
      "soundscapes",
      "relaxation",
      "emotional well-being",
      "self-acceptance",
      "confidence boost",
    ],
  },
};
