export const focusAndMentalPerformanceSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Peak Performance: Enhancing Focus and Mental Clarity",
  description:
    "Discover how Saora helps you achieve peak mental performance through sound therapy. Learn about focus techniques, mental training, and natural solutions for better concentration.",
  url: "https://saora.app/solutions/focus-and-mental-performance",
  mainEntity: {
    "@type": "Article",
    headline: "Peak Performance: Enhancing Focus and Mental Clarity",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "focus",
      "mental performance",
      "concentration",
      "productivity",
      "sound therapy",
      "mental clarity",
      "cognitive enhancement",
      "focus techniques",
      "mental training",
      "brain fog",
      "distraction",
      "mind wandering",
      "pomodoro timer",
      "ambient sounds",
      "guided focus",
      "productivity tracking",
      "peak performance",
      "mental well-being",
      "cognitive abilities",
      "focus enhancement",
    ],
  },
};
