export const painManagementSchema = {
  "@context": "https://schema.org",
  "@type": "WebPage",
  name: "Natural Pain Management and Relief",
  description:
    "Discover how Saora helps you manage pain naturally through sound therapy. Learn about relaxation techniques, stress reduction, and mind-body approaches for pain relief.",
  url: "https://saora.app/solutions/pain-management",
  mainEntity: {
    "@type": "Article",
    headline: "Natural Pain Management and Relief",
    image: "https://saora.app/og-image.jpg",
    author: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
    },
    publisher: {
      "@type": "Organization",
      name: "Saora",
      url: "https://saora.app",
      logo: {
        "@type": "ImageObject",
        url: "https://saora.app/logo.png",
      },
    },
    datePublished: "2024-03-20",
    dateModified: "2024-03-20",
    keywords: [
      "pain management",
      "natural pain relief",
      "sound therapy",
      "relaxation",
      "stress reduction",
      "chronic pain",
      "muscle tension",
      "mind-body connection",
      "healing sounds",
      "pain relief",
      "wellness",
      "guided relaxation",
      "sleep improvement",
      "stress management",
      "holistic healing",
      "soundscapes",
      "pain reduction",
      "natural healing",
      "comfort",
      "well-being",
    ],
  },
};
